database:
  environment:
    - MYSQL_ROOT_PASSWORD=SuperSecretPassword123
    - MYSQL_DATABASE=laravel
  image: mysql

web:
  image: composer
  environment:
    - APP_ENV=production
    - DB_HOST=database
    - DB_DATABASE=laravel
    - DB_USERNAME=root
    - DB_PASSWORD=SuperSecretPassword123

  links:
    - database
  volumes:
    - "./code:/opt/my-app"
  ports:
    - "80:80"
  command: "php -S 0.0.0.0:80 -t /opt/my-app/public"