service: blog

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: eu-west-1
  iamRoleStatements:
      - Effect: Allow
        Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
        Resource: "arn:aws:dynamodb:eu-west-1:*:*"


functions:
  webhook:
    handler: endpoints/webhook.process
    events:
        - http:
            path : webhook
            method: post
            cors : true


#    Define function environment variables here
#    environment:
#      variable2: value2

# you can add CloudFormation resource templates here
resources:
 Resources:
   TodosDynamoDbTable:
     Type: 'AWS::DynamoDB::Table'
     Properties:
        AttributeDefinitions:
           -
               AttributeName: id
               AttributeType: S
        KeySchema:
            -
                AttributeName: id
                KeyType: HASH
        ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        TableName : "posts"
