load_balancer:
    image: tutum/haproxy
    links:
        - web
        - phpmyadmin
    ports:
        - "80:80"

cache:
    image: redis

phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    links:
      - database
    environment:
        - PMA_HOST=database
        - PMA_USER=root
        - PMA_PASSWORD=SuperSecretPassword123


database:
    image: mysql
    environment:
        - MYSQL_ROOT_PASSWORD=SuperSecretPassword123
        - MYSQL_DATABASE=laravel

web:
    image: andrewmclagan/nginx-hhvm
    links:
        - database
        - cache
    volumes:
        - ./:/var/www
    environment:
        - APP_ENV=production
        - DB_HOST=database
        - DB_DATABASE=laravel
        - DB_USERNAME=root
        - DB_PASSWORD=SuperSecretPassword123
        - VIRTUAL_HOST=laravel.local
