redis:
  image: tenstartups/redis:latest
  container_name: redis

load_balancer:
  image: tutum/haproxy
  links:
    - webserver
  ports:
    - "80:80"

mysql:
  image: mysql:5.7
  container_name: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=homestead
    - MYSQL_USER=homestead
    - MYSQL_PASSWORD=secret

webserver:
  build: .
  dockerfile: 3party/Dockerfile
  volumes:
      - ./code:/var/www/
  links:
    - mysql
    - redis
