load_balancer:
  image: tutum/haproxy
  links:
    - web
  ports:
    - "80:80"
  environment:
    - VIRTUAL_HOST=192.168.99.100

web:
    image: skiychan/nginx-php7
    volumes:
        - "./code:/data/www"
