database:
  environment:
    - MYSQL_ROOT_PASSWORD=SuperSecretPassword123
    - MYSQL_DATABASE=laravel
  image: mysql

load_balancer:
  image: tutum/haproxy
  links:
    - web
  ports:
    - "80:80"

web:
  environment:
    - APP_ENV=production
    - DB_HOST=database
    - DB_DATABASE=laravel
    - DB_USERNAME=root
    - DB_PASSWORD=SuperSecretPassword123

  image: andrewmclagan/nginx-hhvm
  links:
    - database
  volumes:
    - "./pagekit:/var/www/public"
